---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: app-fooday
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app-fooday
    spec:
      containers:
        - image: fooday:latest
          imagePullPolicy: Never
          name: fooday
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: app-fooday
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP