apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: app-fooday
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP